[env]
framework = arduino
monitor_filters =
    send_on_enter
    direct
monitor_echo = yes

[env:stick]
platform = atmelavr
board = nanoatmega328
build_src_filter =
    +<shared/>
    +<stick/>

[env:base]
platform = ststm32
board = blackpill_f401cc
upload_protocol = dfu
build_flags = 
    -DUSE_TINYUSB
    -DPIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_PRINTF
build_src_filter =
    +<shared/>
    +<base/>
lib_deps =
    https://github.com/code-fiasco/Adafruit_TinyUSB_Arduino.git#stm32-support-v2