[env]
framework = arduino
monitor_filters =
    send_on_enter
    direct
monitor_echo = yes

[env:stick]
platform = atmelavr
board = nanoatmega328
build_src_filter =
    +<shared/>
    +<stick/>

[env:base]
platform = ststm32
board = blackpill_f401cc
upload_protocol = dfu
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
build_src_filter =
    +<shared/>
    +<base/>